### ISSUE TITLE
Clicking on Aethernet points make map flicker and does not teleport to Main Aetheryte anymore

### ISSUE THREAD

**Issue by Atroskelis** [MidoriKami/Mappy#185]
Par example

Open map
click on Fishermen's guild in Limsa
Map flickers, does nothing

V 3.1.0.4

Can be reproduced easily. This used to work before update.

**Comment by MidoriKami** [comment]
Please include dalamud.log
Any kind of flickering is generally caused by errors being thrown and logged.

**Comment by Atroskelis** [comment]
[dalamud.log](https://github.com/user-attachments/files/17894702/dalamud.log)

Here is the dalamud.log attached.

If i may i'll post the error that appears to log when the flickers happen

``` 2024-11-24 22:11:14.170 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMS0yNFQyMjoxMToxNC4xNzA3NDc4KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IEV4Y2VwdGlvbiBvZiB0eXBlICdTeXN0ZW0uQXJndW1lbnRPdXRPZlJhbmdlRXhjZXB0aW9uJyB3YXMgdGhyb3duLiAoUGFyYW1ldGVyICdyb3dJZCcpXHJcbkFjdHVhbCB2YWx1ZSB3YXMgNzgyLlxyXG4gICBhdCBMdW1pbmEuRXhjZWwuRXhjZWxTaGVldGAxLkdldFJvdyhVSW50MzIgcm93SWQpXHJcbiAgIGF0IEthbWlMaWIuQ2xhc3Nlcy5UZWxlcG9ydGVyLlRlbGVwb3J0KFVJbnQzMiBhZXRoZXJ5dGVJZCkgaW4gL3dvcmsvcmVwby9LYW1pTGliL0NsYXNzZXMvVGVsZXBvcnRlci5jczpsaW5lIDIzXHJcbiAgIGF0IE1hcHB5LkNsYXNzZXMuRHJhd0hlbHBlcnMuUHJvY2Vzc0ludGVyYWN0aW9ucyhNYXJrZXJJbmZvIG1hcmtlckluZm8pIGluIC93b3JrL3JlcG8vTWFwcHkvQ2xhc3Nlcy9EcmF3SGVscGVycy5jczpsaW5lIDE4NFxyXG4gICBhdCBNYXBweS5DbGFzc2VzLkRyYXdIZWxwZXJzLkRyYXdNYXBNYXJrZXIoTWFya2VySW5mbyBtYXJrZXJJbmZvKSBpbiAvd29yay9yZXBvL01hcHB5L0NsYXNzZXMvRHJhd0hlbHBlcnMuY3M6bGluZSAxMDhcclxuICAgYXQgTWFwcHkuRXh0ZW5zaW9ucy5NYXBNYXJrZXJJbmZvRXh0ZW5zaW9ucy5EcmF3KE1hcE1hcmtlckluZm8gbWFya2VyLCBWZWN0b3IyIG9mZnNldCwgU2luZ2xlIHNjYWxlKSBpbiAvd29yay9yZXBvL01hcHB5L0V4dGVuc2lvbnMvTWFwTWFya2VySW5mb0V4dGVuc2lvbnMuY3M6bGluZSA0NFxyXG4gICBhdCBNYXBweS5NYXBSZW5kZXJlci5NYXBSZW5kZXJlci5EcmF3U3RhdGljTWFwTWFya2VycygpIGluIC93b3JrL3JlcG8vTWFwcHkvTWFwUmVuZGVyZXIvTWFwUmVuZGVyZXIuU3RhdGljLmNzOmxpbmUgMTFcclxuICAgYXQgTWFwcHkuTWFwUmVuZGVyZXIuTWFwUmVuZGVyZXIuRHJhd01hcE1hcmtlcnMoKSBpbiAvd29yay9yZXBvL01hcHB5L01hcFJlbmRlcmVyL01hcFJlbmRlcmVyLkNvcmUuY3M6bGluZSAxMDhcclxuICAgYXQgTWFwcHkuV2luZG93cy5NYXBXaW5kb3cuRHJhd0NvbnRlbnRzKCkgaW4gL3dvcmsvcmVwby9NYXBweS9XaW5kb3dzL01hcFdpbmRvdy5jczpsaW5lIDEzM1xyXG4gICBhdCBLYW1pTGliLldpbmRvdy5XaW5kb3cuRHJhdygpIGluIC93b3JrL3JlcG8vS2FtaUxpYi9XaW5kb3cvV2luZG93LmNzOmxpbmUgNzVcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuV2luZG93aW5nLldpbmRvdy5EcmF3SW50ZXJuYWwoRGFsYW11ZENvbmZpZ3VyYXRpb24gY29uZmlndXJhdGlvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcXFxJbnRlcmZhY2VcXFdpbmRvd2luZ1xcV2luZG93LmNzOmxpbmUgMzQ2IiwiQ29udGV4dCI6IltXaW5kb3dTeXN0ZW1dIEVycm9yIGR1cmluZyBEcmF3KCk6IFwiTWFwcHkgTWFwIFdpbmRvdyAtIFRoZSBCbGFjayBTaHJvdWQgLSBOZXcgR3JpZGFuaWEjIyNNYXBweU1hcFdpbmRvd1wiIn0=
2024-11-24 22:11:14.170 +02:00 [ERR] [WindowSystem] Error during Draw(): Mappy Map Window - The Black Shroud - New Gridania###MappyMapWindow
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'rowId')
Actual value was 782.
   at Lumina.Excel.ExcelSheet`1.GetRow(UInt32 rowId)
   at KamiLib.Classes.Teleporter.Teleport(UInt32 aetheryteId) in /work/repo/KamiLib/Classes/Teleporter.cs:line 23
   at Mappy.Classes.DrawHelpers.ProcessInteractions(MarkerInfo markerInfo) in /work/repo/Mappy/Classes/DrawHelpers.cs:line 184
   at Mappy.Classes.DrawHelpers.DrawMapMarker(MarkerInfo markerInfo) in /work/repo/Mappy/Classes/DrawHelpers.cs:line 108
   at Mappy.Extensions.MapMarkerInfoExtensions.Draw(MapMarkerInfo marker, Vector2 offset, Single scale) in /work/repo/Mappy/Extensions/MapMarkerInfoExtensions.cs:line 44
   at Mappy.MapRenderer.MapRenderer.DrawStaticMapMarkers() in /work/repo/Mappy/MapRenderer/MapRenderer.Static.cs:line 11
   at Mappy.MapRenderer.MapRenderer.DrawMapMarkers() in /work/repo/Mappy/MapRenderer/MapRenderer.Core.cs:line 108
   at Mappy.Windows.MapWindow.DrawContents() in /work/repo/Mappy/Windows/MapWindow.cs:line 133
   at KamiLib.Window.Window.Draw() in /work/repo/KamiLib/Window/Window.cs:line 75
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
```
